### PR TITLE
Implementing missing RPC API 

### PR DESCRIPTION
**Pull request by juliavi**
Implementing 
- getbalance
- getnewaddress
- listaddress
- sendtoaddress

### CODE REVIEW

**Comment by juliavi** [comment]
@BrunoFreitasgit  can you please review?

**Comment by juliavi** [comment]
@BrunoFreitasgit  I'm adding tests.
Regarding the CLI - these methods throw a meaningful exception of 'access denied' when the wallet isn't open.  So this situation can be easily identified

**Comment by BrunoFreitasgit** [comment]
But those methods are only helpful if there is an integration, and right now there is no way to open a wallet remotely by using the rpc nodes, that's why they were not implemented in the first place. So, for now, that would not add value to the library.

**Comment by juliavi** [comment]
They are helpful if the API is running against a node with an open wallet.
Since this is the use case of all the people who will use this API - we can leave error handling up to the them.
In the current situation, everyone using this API will have to implement these methods themselves, and for wallet and exchange developers they are vital.

**Comment by BrunoFreitasgit** [comment]
I don't think the only use case of all the people for this api is to use it on a local open wallet on a local rpc node, but to use it as a light client (for mobile apps, data gathering, statistics, etc). If people are using this for operations on a local node, why wouldn't they use neo-cli instead?
But anyway, add the tests (they can be simple like the ones on the project) and I will review it. 
Thanks for the contribution!

**Comment by juliavi** [comment]
I've added tests, please review and approve :)
The reason this API is so useful to a lot of us is that while developing a trading platform or exchange you need to access your hosted node and wallet, and the missing api methods are exactly the ones you need in your web interface - getting the balance/new address etc.
CLI won't help here - As described in the official document for exchange developers:
http://docs.neo.org/en-us/exchange.html
Thank you!

**Comment by juliavi** [comment]
Done

**Comment by BrunoFreitasgit** [comment]
@juliavi merged and the changes are implemented on the new nuget version https://www.nuget.org/packages/NeoModules.RPC/1.0.5

**Pull request merged**
